In [1]:
import pandas as pd
import numpy as np

In [2]:
#Load the dataset nba_attendance
nba_attendance = pd.read_csv('../../mast30034-project-1-dustintano10/data/raw/nba_attendance_2018_2019.csv')

In [3]:
#preprocess the attendance dataset by removing irrelevant columns and filtering it to New York playing at Home
nba_attendance = nba_attendance.drop(nba_attendance.columns[[6,7,10]],axis = 1)
nba_attendance = nba_attendance[nba_attendance['Home/Neutral'] == 'New York Knicks']

In [4]:
nba_attendance['Win'] = np.where((nba_attendance['PTS.1'] > nba_attendance['PTS'] ), 'Yes', 'No')
nba_attendance

,Date,Start (ET),Visitor/Neutral,PTS,Home/Neutral,PTS.1,Attend.,Arena,Win
6,Wed Oct 17 2018,7:30p,Atlanta Hawks,107,New York Knicks,126,18249,Madison Square Garden (IV),Yes
27,Sat Oct 20 2018,7:30p,Boston Celtics,103,New York Knicks,101,19427,Madison Square Garden (IV),No
67,Fri Oct 26 2018,7:30p,Golden State Warriors,128,New York Knicks,100,19812,Madison Square Garden (IV),No
89,Mon Oct 29 2018,7:30p,Brooklyn Nets,96,New York Knicks,115,19221,Madison Square Garden (IV),Yes
106,Wed Oct 31 2018,8:00p,Indiana Pacers,107,New York Knicks,101,18295,Madison Square Garden (IV),No
142,Mon Nov 5 2018,7:30p,Chicago Bulls,116,New York Knicks,115,19812,Madison Square Garden (IV),No
185,Sun Nov 11 2018,7:30p,Orlando Magic,115,New York Knicks,89,19812,Madison Square Garden (IV),No
250,Tue Nov 20 2018,7:30p,Portland Trail Blazers,118,New York Knicks,114,19812,Madison Square Garden (IV),No
268,Fri Nov 23 2018,7:30p,New Orleans Pelicans,109,New York Knicks,114,18948,Madison Square Garden (IV),Yes
329,Sat Dec 1 2018,5:00p,Milwaukee Bucks,134,New York Knicks,136,19812,Madison Square Garden (IV),Yes
345,Mon Dec 3 2018,7:30p,Washington Wizards,110,New York Knicks,107,19440,Madison Square Garden (IV),No
381,Sat Dec 8 2018,7:30p,Brooklyn Nets,112,New York Knicks,104,18662,Madison Square Garden (IV),No
389,Sun Dec 9 2018,7:30p,Charlotte Hornets,119,New York Knicks,107,18602,Madison Square Garden (IV),No
443,Mon Dec 17 2018,7:30p,Phoenix Suns,128,New York Knicks,110,18437,Madison Square Garden (IV),No
471,Fri Dec 21 2018,7:30p,Atlanta Hawks,114,New York Knicks,107,19080,Madison Square Garden (IV),No
496,Tue Dec 25 2018,12:00p,Milwaukee Bucks,109,New York Knicks,95,19812,Madison Square Garden (IV),No
622,Fri Jan 11 2019,7:30p,Indiana Pacers,121,New York Knicks,106,19812,Madison Square Garden (IV),No
637,Sun Jan 13 2019,1:00p,Philadelphia 76ers,108,New York Knicks,105,18596,Madison Square Garden (IV),No
690,Mon Jan 21 2019,12:30p,Oklahoma City Thunder,127,New York Knicks,109,19493,Madison Square Garden (IV),No
709,Wed Jan 23 2019,7:30p,Houston Rockets,114,New York Knicks,110,18819,Madison Square Garden (IV),No
741,Sun Jan 27 2019,7:30p,Miami Heat,106,New York Knicks,97,18852,Madison Square Garden (IV),No
757,Wed Jan 30 2019,7:30p,Dallas Mavericks,114,New York Knicks,90,18842,Madison Square Garden (IV),No
770,Fri Feb 1 2019,7:30p,Boston Celtics,113,New York Knicks,99,18343,Madison Square Garden (IV),No
786,Sun Feb 3 2019,1:00p,Memphis Grizzlies,96,New York Knicks,84,17025,Madison Square Garden (IV),No
798,Tue Feb 5 2019,7:30p,Detroit Pistons,105,New York Knicks,92,17853,Madison Square Garden (IV),No
827,Sat Feb 9 2019,7:30p,Toronto Raptors,104,New York Knicks,99,18886,Madison Square Garden (IV),No
855,Wed Feb 13 2019,7:30p,Philadelphia 76ers,126,New York Knicks,111,18983,Madison Square Garden (IV),No
877,Fri Feb 22 2019,7:30p,Minnesota Timberwolves,115,New York Knicks,104,19096,Madison Square Garden (IV),No
895,Sun Feb 24 2019,7:30p,San Antonio Spurs,118,New York Knicks,130,18019,Madison Square Garden (IV),Yes
907,Tue Feb 26 2019,7:30p,Orlando Magic,103,New York Knicks,108,17833,Madison Square Garden (IV),Yes
923,Thu Feb 28 2019,7:30p,Cleveland Cavaliers,125,New York Knicks,118,17573,Madison Square Garden (IV),No
985,Sat Mar 9 2019,12:00p,Sacramento Kings,102,New York Knicks,94,19812,Madison Square Garden (IV),No
1041,Sun Mar 17 2019,12:00p,Los Angeles Lakers,123,New York Knicks,124,19812,Madison Square Garden (IV),Yes
1067,Wed Mar 20 2019,7:30p,Utah Jazz,137,New York Knicks,116,18530,Madison Square Garden (IV),No
1081,Fri Mar 22 2019,7:30p,Denver Nuggets,111,New York Knicks,93,19290,Madison Square Garden (IV),No
1094,Sun Mar 24 2019,12:00p,Los Angeles Clippers,124,New York Knicks,113,18263,Madison Square Garden (IV),No
1124,Thu Mar 28 2019,7:30p,Toronto Raptors,117,New York Knicks,92,19812,Madison Square Garden (IV),No
1140,Sat Mar 30 2019,7:30p,Miami Heat,100,New York Knicks,92,19812,Madison Square Garden (IV),No
1154,Mon Apr 1 2019,7:30p,Chicago Bulls,105,New York Knicks,113,18874,Madison Square Garden (IV),Yes
1203,Sun Apr 7 2019,7:30p,Washington Wizards,110,New York Knicks,113,19812,Madison Square Garden (IV),Yes
1224,Wed Apr 10 2019,8:00p,Detroit Pistons,115,New York Knicks,89,19812,Madison Square Garden (IV),No

In [5]:
# create new columns for individual month, day and year
# purpose is to create a new date column which has the same date format with the taxi dataset

nba_attendance['Start (ET)'] = nba_attendance['Start (ET)'].str[:-1]

nba_attendance['Month'] = nba_attendance['Date'].str[4:7]

nba_attendance['Day'] = nba_attendance['Date'].str[8:10]

nba_attendance['Year'] = nba_attendance['Date'].str[10:15]

nba_attendance['Day'] = nba_attendance['Day'].str.replace(' ', '')

nba_attendance['Day'] = nba_attendance['Day'].str.zfill(2)

In [6]:
# dictionary to convert month in the form of text to number format
# form would still be a string

month_to_num = {'Oct' : '10', 'Nov' : '11', 'Dec' : '12', 'Jan' : '01', 'Feb' : '02', 'Mar' : '03', 'Apr' : '04'}

nba_attendance['Month'] = nba_attendance['Month'].replace(month_to_num)
nba_attendance

,Date,Start (ET),Visitor/Neutral,PTS,Home/Neutral,PTS.1,Attend.,Arena,Win,Month,Day,Year
6,Wed Oct 17 2018,7:30,Atlanta Hawks,107,New York Knicks,126,18249,Madison Square Garden (IV),Yes,10,17,2018
27,Sat Oct 20 2018,7:30,Boston Celtics,103,New York Knicks,101,19427,Madison Square Garden (IV),No,10,20,2018
67,Fri Oct 26 2018,7:30,Golden State Warriors,128,New York Knicks,100,19812,Madison Square Garden (IV),No,10,26,2018
89,Mon Oct 29 2018,7:30,Brooklyn Nets,96,New York Knicks,115,19221,Madison Square Garden (IV),Yes,10,29,2018
106,Wed Oct 31 2018,8:00,Indiana Pacers,107,New York Knicks,101,18295,Madison Square Garden (IV),No,10,31,2018
142,Mon Nov 5 2018,7:30,Chicago Bulls,116,New York Knicks,115,19812,Madison Square Garden (IV),No,11,05,2018
185,Sun Nov 11 2018,7:30,Orlando Magic,115,New York Knicks,89,19812,Madison Square Garden (IV),No,11,11,2018
250,Tue Nov 20 2018,7:30,Portland Trail Blazers,118,New York Knicks,114,19812,Madison Square Garden (IV),No,11,20,2018
268,Fri Nov 23 2018,7:30,New Orleans Pelicans,109,New York Knicks,114,18948,Madison Square Garden (IV),Yes,11,23,2018
329,Sat Dec 1 2018,5:00,Milwaukee Bucks,134,New York Knicks,136,19812,Madison Square Garden (IV),Yes,12,01,2018
345,Mon Dec 3 2018,7:30,Washington Wizards,110,New York Knicks,107,19440,Madison Square Garden (IV),No,12,03,2018
381,Sat Dec 8 2018,7:30,Brooklyn Nets,112,New York Knicks,104,18662,Madison Square Garden (IV),No,12,08,2018
389,Sun Dec 9 2018,7:30,Charlotte Hornets,119,New York Knicks,107,18602,Madison Square Garden (IV),No,12,09,2018
443,Mon Dec 17 2018,7:30,Phoenix Suns,128,New York Knicks,110,18437,Madison Square Garden (IV),No,12,17,2018
471,Fri Dec 21 2018,7:30,Atlanta Hawks,114,New York Knicks,107,19080,Madison Square Garden (IV),No,12,21,2018
496,Tue Dec 25 2018,12:00,Milwaukee Bucks,109,New York Knicks,95,19812,Madison Square Garden (IV),No,12,25,2018
622,Fri Jan 11 2019,7:30,Indiana Pacers,121,New York Knicks,106,19812,Madison Square Garden (IV),No,01,11,2019
637,Sun Jan 13 2019,1:00,Philadelphia 76ers,108,New York Knicks,105,18596,Madison Square Garden (IV),No,01,13,2019
690,Mon Jan 21 2019,12:30,Oklahoma City Thunder,127,New York Knicks,109,19493,Madison Square Garden (IV),No,01,21,2019
709,Wed Jan 23 2019,7:30,Houston Rockets,114,New York Knicks,110,18819,Madison Square Garden (IV),No,01,23,2019
741,Sun Jan 27 2019,7:30,Miami Heat,106,New York Knicks,97,18852,Madison Square Garden (IV),No,01,27,2019
757,Wed Jan 30 2019,7:30,Dallas Mavericks,114,New York Knicks,90,18842,Madison Square Garden (IV),No,01,30,2019
770,Fri Feb 1 2019,7:30,Boston Celtics,113,New York Knicks,99,18343,Madison Square Garden (IV),No,02,01,2019
786,Sun Feb 3 2019,1:00,Memphis Grizzlies,96,New York Knicks,84,17025,Madison Square Garden (IV),No,02,03,2019
798,Tue Feb 5 2019,7:30,Detroit Pistons,105,New York Knicks,92,17853,Madison Square Garden (IV),No,02,05,2019
827,Sat Feb 9 2019,7:30,Toronto Raptors,104,New York Knicks,99,18886,Madison Square Garden (IV),No,02,09,2019
855,Wed Feb 13 2019,7:30,Philadelphia 76ers,126,New York Knicks,111,18983,Madison Square Garden (IV),No,02,13,2019
877,Fri Feb 22 2019,7:30,Minnesota Timberwolves,115,New York Knicks,104,19096,Madison Square Garden (IV),No,02,22,2019
895,Sun Feb 24 2019,7:30,San Antonio Spurs,118,New York Knicks,130,18019,Madison Square Garden (IV),Yes,02,24,2019
907,Tue Feb 26 2019,7:30,Orlando Magic,103,New York Knicks,108,17833,Madison Square Garden (IV),Yes,02,26,2019
923,Thu Feb 28 2019,7:30,Cleveland Cavaliers,125,New York Knicks,118,17573,Madison Square Garden (IV),No,02,28,2019
985,Sat Mar 9 2019,12:00,Sacramento Kings,102,New York Knicks,94,19812,Madison Square Garden (IV),No,03,09,2019
1041,Sun Mar 17 2019,12:00,Los Angeles Lakers,123,New York Knicks,124,19812,Madison Square Garden (IV),Yes,03,17,2019
1067,Wed Mar 20 2019,7:30,Utah Jazz,137,New York Knicks,116,18530,Madison Square Garden (IV),No,03,20,2019
1081,Fri Mar 22 2019,7:30,Denver Nuggets,111,New York Knicks,93,19290,Madison Square Garden (IV),No,03,22,2019
1094,Sun Mar 24 2019,12:00,Los Angeles Clippers,124,New York Knicks,113,18263,Madison Square Garden (IV),No,03,24,2019
1124,Thu Mar 28 2019,7:30,Toronto Raptors,117,New York Knicks,92,19812,Madison Square Garden (IV),No,03,28,2019
1140,Sat Mar 30 2019,7:30,Miami Heat,100,New York Knicks,92,19812,Madison Square Garden (IV),No,03,30,2019
1154,Mon Apr 1 2019,7:30,Chicago Bulls,105,New York Knicks,113,18874,Madison Square Garden (IV),Yes,04,01,2019
1203,Sun Apr 7 2019,7:30,Washington Wizards,110,New York Knicks,113,19812,Madison Square Garden (IV),Yes,04,07,2019
1224,Wed Apr 10 2019,8:00,Detroit Pistons,115,New York Knicks,89,19812,Madison Square Garden (IV),No,04,10,2019

In [7]:
# combine the 3 new columns to one as a new date format year-month-day
# I didn't convert it to a date format due to problems when trying to merge it with taxi dataset
# so I converted it in the taxi preprocessing

nba_attendance = nba_attendance.assign(Date = nba_attendance.Year.astype('string') +\
                                      nba_attendance.Month.astype('string') +\
                                      nba_attendance.Day.astype('string'))

# added a margin_victory and margin_loss attribute to see how big are the point difference in wins and losses
nba_attendance.loc[nba_attendance['PTS'] - nba_attendance['PTS.1'] > 0 , 'Margin_loss'] = nba_attendance['PTS'] - nba_attendance['PTS.1']

nba_attendance.loc[nba_attendance['PTS.1'] - nba_attendance['PTS'] > 0 , 'Margin_victory'] = nba_attendance['PTS.1'] - nba_attendance['PTS']

nba_attendance

,Date,Start (ET),Visitor/Neutral,PTS,Home/Neutral,PTS.1,Attend.,Arena,Win,Month,Day,Year,Margin_loss,Margin_victory
6,20181017,7:30,Atlanta Hawks,107,New York Knicks,126,18249,Madison Square Garden (IV),Yes,10,17,2018,NaN,19.0
27,20181020,7:30,Boston Celtics,103,New York Knicks,101,19427,Madison Square Garden (IV),No,10,20,2018,2.0,NaN
67,20181026,7:30,Golden State Warriors,128,New York Knicks,100,19812,Madison Square Garden (IV),No,10,26,2018,28.0,NaN
89,20181029,7:30,Brooklyn Nets,96,New York Knicks,115,19221,Madison Square Garden (IV),Yes,10,29,2018,NaN,19.0
106,20181031,8:00,Indiana Pacers,107,New York Knicks,101,18295,Madison Square Garden (IV),No,10,31,2018,6.0,NaN
142,20181105,7:30,Chicago Bulls,116,New York Knicks,115,19812,Madison Square Garden (IV),No,11,05,2018,1.0,NaN
185,20181111,7:30,Orlando Magic,115,New York Knicks,89,19812,Madison Square Garden (IV),No,11,11,2018,26.0,NaN
250,20181120,7:30,Portland Trail Blazers,118,New York Knicks,114,19812,Madison Square Garden (IV),No,11,20,2018,4.0,NaN
268,20181123,7:30,New Orleans Pelicans,109,New York Knicks,114,18948,Madison Square Garden (IV),Yes,11,23,2018,NaN,5.0
329,20181201,5:00,Milwaukee Bucks,134,New York Knicks,136,19812,Madison Square Garden (IV),Yes,12,01,2018,NaN,2.0
345,20181203,7:30,Washington Wizards,110,New York Knicks,107,19440,Madison Square Garden (IV),No,12,03,2018,3.0,NaN
381,20181208,7:30,Brooklyn Nets,112,New York Knicks,104,18662,Madison Square Garden (IV),No,12,08,2018,8.0,NaN
389,20181209,7:30,Charlotte Hornets,119,New York Knicks,107,18602,Madison Square Garden (IV),No,12,09,2018,12.0,NaN
443,20181217,7:30,Phoenix Suns,128,New York Knicks,110,18437,Madison Square Garden (IV),No,12,17,2018,18.0,NaN
471,20181221,7:30,Atlanta Hawks,114,New York Knicks,107,19080,Madison Square Garden (IV),No,12,21,2018,7.0,NaN
496,20181225,12:00,Milwaukee Bucks,109,New York Knicks,95,19812,Madison Square Garden (IV),No,12,25,2018,14.0,NaN
622,20190111,7:30,Indiana Pacers,121,New York Knicks,106,19812,Madison Square Garden (IV),No,01,11,2019,15.0,NaN
637,20190113,1:00,Philadelphia 76ers,108,New York Knicks,105,18596,Madison Square Garden (IV),No,01,13,2019,3.0,NaN
690,20190121,12:30,Oklahoma City Thunder,127,New York Knicks,109,19493,Madison Square Garden (IV),No,01,21,2019,18.0,NaN
709,20190123,7:30,Houston Rockets,114,New York Knicks,110,18819,Madison Square Garden (IV),No,01,23,2019,4.0,NaN
741,20190127,7:30,Miami Heat,106,New York Knicks,97,18852,Madison Square Garden (IV),No,01,27,2019,9.0,NaN
757,20190130,7:30,Dallas Mavericks,114,New York Knicks,90,18842,Madison Square Garden (IV),No,01,30,2019,24.0,NaN
770,20190201,7:30,Boston Celtics,113,New York Knicks,99,18343,Madison Square Garden (IV),No,02,01,2019,14.0,NaN
786,20190203,1:00,Memphis Grizzlies,96,New York Knicks,84,17025,Madison Square Garden (IV),No,02,03,2019,12.0,NaN
798,20190205,7:30,Detroit Pistons,105,New York Knicks,92,17853,Madison Square Garden (IV),No,02,05,2019,13.0,NaN
827,20190209,7:30,Toronto Raptors,104,New York Knicks,99,18886,Madison Square Garden (IV),No,02,09,2019,5.0,NaN
855,20190213,7:30,Philadelphia 76ers,126,New York Knicks,111,18983,Madison Square Garden (IV),No,02,13,2019,15.0,NaN
877,20190222,7:30,Minnesota Timberwolves,115,New York Knicks,104,19096,Madison Square Garden (IV),No,02,22,2019,11.0,NaN
895,20190224,7:30,San Antonio Spurs,118,New York Knicks,130,18019,Madison Square Garden (IV),Yes,02,24,2019,NaN,12.0
907,20190226,7:30,Orlando Magic,103,New York Knicks,108,17833,Madison Square Garden (IV),Yes,02,26,2019,NaN,5.0
923,20190228,7:30,Cleveland Cavaliers,125,New York Knicks,118,17573,Madison Square Garden (IV),No,02,28,2019,7.0,NaN
985,20190309,12:00,Sacramento Kings,102,New York Knicks,94,19812,Madison Square Garden (IV),No,03,09,2019,8.0,NaN
1041,20190317,12:00,Los Angeles Lakers,123,New York Knicks,124,19812,Madison Square Garden (IV),Yes,03,17,2019,NaN,1.0
1067,20190320,7:30,Utah Jazz,137,New York Knicks,116,18530,Madison Square Garden (IV),No,03,20,2019,21.0,NaN
1081,20190322,7:30,Denver Nuggets,111,New York Knicks,93,19290,Madison Square Garden (IV),No,03,22,2019,18.0,NaN
1094,20190324,12:00,Los Angeles Clippers,124,New York Knicks,113,18263,Madison Square Garden (IV),No,03,24,2019,11.0,NaN
1124,20190328,7:30,Toronto Raptors,117,New York Knicks,92,19812,Madison Square Garden (IV),No,03,28,2019,25.0,NaN
1140,20190330,7:30,Miami Heat,100,New York Knicks,92,19812,Madison Square Garden (IV),No,03,30,2019,8.0,NaN
1154,20190401,7:30,Chicago Bulls,105,New York Knicks,113,18874,Madison Square Garden (IV),Yes,04,01,2019,NaN,8.0
1203,20190407,7:30,Washington Wizards,110,New York Knicks,113,19812,Madison Square Garden (IV),Yes,04,07,2019,NaN,3.0
1224,20190410,8:00,Detroit Pistons,115,New York Knicks,89,19812,Madison Square Garden (IV),No,04,10,2019,26.0,NaN

In [8]:
# remove even more irrelevant columns as we only need these columns

nba_attendance = nba_attendance.drop(nba_attendance.columns[[2, 3, 4, 5, 7, 9, 10,11]], axis=1)

nba_attendance

           Date Start (ET)  Attend.  Win  Margin_loss  Margin_victory
6      20181017       7:30    18249  Yes          NaN            19.0
27     20181020       7:30    19427   No          2.0             NaN
67     20181026       7:30    19812   No         28.0             NaN
89     20181029       7:30    19221  Yes          NaN            19.0
106    20181031       8:00    18295   No          6.0             NaN
142    20181105       7:30    19812   No          1.0             NaN
185    20181111       7:30    19812   No         26.0             NaN
250    20181120       7:30    19812   No          4.0             NaN
268    20181123       7:30    18948  Yes          NaN             5.0
329    20181201       5:00    19812  Yes          NaN             2.0
345    20181203       7:30    19440   No          3.0             NaN
381    20181208       7:30    18662   No          8.0             NaN
389    20181209       7:30    18602   No         12.0             NaN
443    20181217       7:30    18437   No         18.0             NaN
471    20181221       7:30    19080   No          7.0             NaN
496    20181225      12:00    19812   No         14.0             NaN
622    20190111       7:30    19812   No         15.0             NaN
637    20190113       1:00    18596   No          3.0             NaN
690    20190121      12:30    19493   No         18.0             NaN
709    20190123       7:30    18819   No          4.0             NaN
741    20190127       7:30    18852   No          9.0             NaN
757    20190130       7:30    18842   No         24.0             NaN
770    20190201       7:30    18343   No         14.0             NaN
786    20190203       1:00    17025   No         12.0             NaN
798    20190205       7:30    17853   No         13.0             NaN
827    20190209       7:30    18886   No          5.0             NaN
855    20190213       7:30    18983   No         15.0             NaN
877    20190222       7:30    19096   No         11.0             NaN
895    20190224       7:30    18019  Yes          NaN            12.0
907    20190226       7:30    17833  Yes          NaN             5.0
923    20190228       7:30    17573   No          7.0             NaN
985    20190309      12:00    19812   No          8.0             NaN
1041   20190317      12:00    19812  Yes          NaN             1.0
1067   20190320       7:30    18530   No         21.0             NaN
1081   20190322       7:30    19290   No         18.0             NaN
1094   20190324      12:00    18263   No         11.0             NaN
1124   20190328       7:30    19812   No         25.0             NaN
1140   20190330       7:30    19812   No          8.0             NaN
1154   20190401       7:30    18874  Yes          NaN             8.0
1203   20190407       7:30    19812  Yes          NaN             3.0
1224   20190410       8:00    19812   No         26.0             NaN

In [9]:
nba_attendance.to_csv('../../mast30034-project-1-dustintano10/data/curated/nba_attendance_new.csv', index = False)
nba_attendance_2 = pd.read_csv('../../mast30034-project-1-dustintano10/data/curated/nba_attendance_new.csv')
nba_attendance_2

        Date Start (ET)  Attend.  Win  Margin_loss  Margin_victory
0   20181017       7:30    18249  Yes          NaN            19.0
1   20181020       7:30    19427   No          2.0             NaN
2   20181026       7:30    19812   No         28.0             NaN
3   20181029       7:30    19221  Yes          NaN            19.0
4   20181031       8:00    18295   No          6.0             NaN
5   20181105       7:30    19812   No          1.0             NaN
6   20181111       7:30    19812   No         26.0             NaN
7   20181120       7:30    19812   No          4.0             NaN
8   20181123       7:30    18948  Yes          NaN             5.0
9   20181201       5:00    19812  Yes          NaN             2.0
10  20181203       7:30    19440   No          3.0             NaN
11  20181208       7:30    18662   No          8.0             NaN
12  20181209       7:30    18602   No         12.0             NaN
13  20181217       7:30    18437   No         18.0             NaN
14  20181221       7:30    19080   No          7.0             NaN
15  20181225      12:00    19812   No         14.0             NaN
16  20190111       7:30    19812   No         15.0             NaN
17  20190113       1:00    18596   No          3.0             NaN
18  20190121      12:30    19493   No         18.0             NaN
19  20190123       7:30    18819   No          4.0             NaN
20  20190127       7:30    18852   No          9.0             NaN
21  20190130       7:30    18842   No         24.0             NaN
22  20190201       7:30    18343   No         14.0             NaN
23  20190203       1:00    17025   No         12.0             NaN
24  20190205       7:30    17853   No         13.0             NaN
25  20190209       7:30    18886   No          5.0             NaN
26  20190213       7:30    18983   No         15.0             NaN
27  20190222       7:30    19096   No         11.0             NaN
28  20190224       7:30    18019  Yes          NaN            12.0
29  20190226       7:30    17833  Yes          NaN             5.0
30  20190228       7:30    17573   No          7.0             NaN
31  20190309      12:00    19812   No          8.0             NaN
32  20190317      12:00    19812  Yes          NaN             1.0
33  20190320       7:30    18530   No         21.0             NaN
34  20190322       7:30    19290   No         18.0             NaN
35  20190324      12:00    18263   No         11.0             NaN
36  20190328       7:30    19812   No         25.0             NaN
37  20190330       7:30    19812   No          8.0             NaN
38  20190401       7:30    18874  Yes          NaN             8.0
39  20190407       7:30    19812  Yes          NaN             3.0
40  20190410       8:00    19812   No         26.0             NaN